### PR TITLE
generate helm chart and publish to registry.

### PR DESCRIPTION
**Pull request by jhmadhav**
# What does this change
_Give a summary of the change, and how it affects end-users. It's okay to copy/paste your commit messages._

It Introduces generateHelmChart and publishHelmChart commands to mage to automatically generate helm chart for operator from installer manifests, update image references and push the chart to registry. On Publishhelmchart - the operator chart will be generated from kustomize build, crds will be copied into crds directory under charts/operator, and rest of the manifests into templates folder in charts/operator/templates and Porter operator namespace configuration onboarding yaml's will be copied into templates and proper templating will be applied supporting helm values making a installable helm chart- programmatically. Helm chart version will be updated based on meta.version and operator helm chart will be pushed to registry for consumption. This opens doors to install operator through helm rather than from bundle and since the crds are generated from operator kustomization, manifests need not be maintained for helm explicitly.

on publishHelmChart (from directory perspective on how files are generated)

image

From CLI perspective - on how chart is published (This will be run on mage publish as well)

image

# What issue does it fix
Closes # _(issue)_

_If there is not an existing issue, please make sure we have context on why this change is needed. See our Contributing Guide for [examples of when an existing issue isn't necessary][1]._

[1]: https://getporter.org/src/CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer
_Put any questions or notes for the reviewer here._

# Checklist
- [ ] Did you write tests?
- [ ] Did you write documentation?
- [ ] Did you make any API changes? Update the corresponding API documentation.

[contributors]: https://getporter.org/src/CONTRIBUTORS.md

### CODE REVIEW

**Comment by jhmadhav** [comment]
@bdegeeter updated can you please check

**Comment by bdegeeter** [comment]
I would expect the to be driven from an issue.  There's no issue associated with this PR.  I appreciate your effort and contribution; however, we need to determine how best to host a helm chart for the operator. Aspects such as maintainability and publishing need to be considered as part of a change like this.   A helm chart will need to be versioned and published separately from the operator.  It's not uncommon to see them maintained in a separate versioned git repo. 

We need to consider the need to publish a new version of a helm chart when there no functional change to the operator.  It appears this change is coupling the helm chart version to the porter operator version.  There are patterns for maintaining and hosting helm and kustomize form a single source of true that I’d like to see us review. 

https://www.linkedin.com/pulse/using-helm-chart-kustomize-managing-multiple-microservices/

We want to meet users where they are at when installing the operator which means having a development workflow to produce a helm chart, kustomize and porter bundle for operator installation.  Let's review this and take it from there.

**Comment by squillace** [comment]
Your point is correct, @bdegeeter, and here's the issue: https://github.com/getporter/operator/issues/75. I note that Carolyn was interested a year ago in both helm and kustomize solutions so that users could install things _using the tool that they wanted to use BEFORE they had porter_. That's the only motivation here: to support the widest class of possible users. Carolyn was always into inclusion. :-|

That said, I'll pick up the thread in that issue and give some user data that describes why helm is one of the most important operation tools in the entire ecosystem (which of course is the only reason to support it). 

but NOTE: that is different than merging this PR as-is. I've had a look and I don't actually like the way it's done, so my suggestion for what it's worth is to sit on this, extract the proper method of doing things, and place that implementation somewhere where it doesn't affect other users. There's no hurry here. My two cents......

**Comment by jhmadhav** [comment]
I appreciate your feedback on this. @bdegeeter, @squillace and @schristoff.  I agree with aspects of maintainability as everyone rightly pointed. Thanks @squillace for finding the issue :)  I remember having some discussions related to helm charts with Carlolyn but could not find the issue to link to this PR. I agree that this approach is not viable for generation of complex helm templating, and we need a maintainable way to produce helm charts.  Consider this is just an attempt to quickly generate charts from kustomize without maintaining two sources and apply helm templating to generated manifests, just as described in [Issue: #75](https://github.com/getporter/operator/issues/75). I really appreciate spending some time in community meeting on maintaining helm charts too. @schristoff. I embrace both helm and kustomize, and kustomization is already provided by kubebuilder out of box. Adding to @squillace, supporting helm charts would greatly help users relying on helm way of deploying and would encourage them to try Porter.

**Comment by schristoff** [comment]
I have moved this to [deployments](github.com/getporter/deployments)

**Pull request closed without merging**
